### NumPy Array Operations and Descriptions 🧮✨

In [1]:
import numpy as np  # Importing the numpy module

def describe(ar):
    """Print out a summary of an array."""
    print(f'dimensions: {ar.ndim}')  # Print the number of dimensions
    print(f'shape: {ar.shape}')  # Print the shape of the array
    print(f'size: {ar.size}')  # Print the total number of elements
    print(f'dtype: {ar.dtype}')  # Print the data type of the elements

list1 = [1, 2, 3]  # Create a Python list
list2 = [4, 5, 6]  # Create another Python list
arr = np.array((1, 2, 3, 4))  # Create a numpy array from a tuple
# Output: array([1, 2, 3, 4])

arr2 = np.array([list1, list2], dtype=np.float64)  # Create a 2D numpy array with specified data type
# Output: array([[1., 2., 3.],
#                [4., 5., 6.]])

arr3 = np.ones((2, 2))  # Create a 2x2 numpy array filled with ones
# Output: array([[1., 1.],
#                [1., 1.]])

arr4 = np.zeros((4, 3))  # Create a 4x3 numpy array filled with zeros
# Output: array([[0., 0., 0.],
#                [0., 0., 0.],
#                [0., 0., 0.],
#                [0., 0., 0.]])

arr5 = np.arange(10)  # Create a numpy array with values from 0 to 9
# Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr6 = np.linspace(0, 30, 31)  # Create a numpy array with 31 evenly spaced values from 0 to 30
# Output: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
#                13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
#                26., 27., 28., 29., 30.])

arr7 = np.random.rand(2, 3)  # Create a 2x3 numpy array with random values from a uniform distribution
# Output: array([[0.123, 0.456, 0.789],  # Random values will vary
#                [0.101, 0.112, 0.131]])

arr8 = arr4.reshape(12)  # Reshape arr4 into a 1D numpy array with 12 elements
# Output: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

arr9 = np.ones_like(arr8)  # Create a numpy array with the same shape and data type as arr8 filled with ones
# Output: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

arr10 = np.full(shape=(2, 2, 6), fill_value=8)  # Create a 3D numpy array with shape (2, 2, 6) filled with eights
# Output: array([[[8, 8, 8, 8, 8, 8],
#                 [8, 8, 8, 8, 8, 8]],
#                [[8, 8, 8, 8, 8, 8],
#                 [8, 8, 8, 8, 8, 8]]])

arr11 = np.eye(N=5)  # Create a 5x5 identity matrix
# Output: array([[1., 0., 0., 0., 0.],
#                [0., 1., 0., 0., 0.],
#                [0., 0., 1., 0., 0.],
#                [0., 0., 0., 1., 0.],
#                [0., 0., 0., 0., 1.]])

print(arr11)  # Print the array arr11
# Output: [[1. 0. 0. 0. 0.]
#          [0. 1. 0. 0. 0.]
#          [0. 0. 1. 0. 0.]
#          [0. 0. 0. 1. 0.]
#          [0. 0. 0. 0. 1.]]

describe(arr11)  # Call the describe function to print summary information about arr11
# Output: dimensions: 2
#         shape: (5, 5)
#         size: 25
#         dtype: float64

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
dimensions: 2
shape: (5, 5)
size: 25
dtype: float64


### NumPy Array Operations and Statistics 🧮✨

In [2]:
import numpy as np  # Importing the numpy module

# Creating numpy arrays
a = np.array([1, 2, 3, 4, 5])  # Array 'a' containing integers
b = np.array([1.0, 2.0, 1.0, 2.0, 1.0])  # Array 'b' containing floating-point numbers

# Printing arrays
print('a:', a)  # Print array 'a'
# Output: a: [1 2 3 4 5]
print('b:', b)  # Print array 'b'
# Output: b: [1. 0. 1. 0. 1.]

# Element-wise operations
print('a + b:', a + b)  # Element-wise addition
# Output: a + b: [2. 2. 4. 4. 6.]
print('a - b:', a - b)  # Element-wise subtraction
# Output: a - b: [0. 2. 2. 4. 4.]
print('a * b:', a * b)  # Element-wise multiplication
# Output: a * b: [1. 0. 3. 0. 5.]
print('a / b:', a / b)  # Element-wise division
# Output: a / b: [ 1. inf  3. inf  5.] (Note: division by zero produces inf)
print('-' * 40)  # Print a separator line
# Output: ----------------------------------------

# Scalar operations
print('a + 10:', a + 10)  # Scalar addition
# Output: a + 10: [11 12 13 14 15]
print('a - 10:', a - 10)  # Scalar subtraction
# Output: a - 10: [-9 -8 -7 -6 -5]
print('a * 10:', a * 10)  # Scalar multiplication
# Output: a * 10: [10 20 30 40 50]
print('a / 10:', a / 10)  # Scalar division
# Output: a / 10: [0.1 0.2 0.3 0.4 0.5]
print('a ** 2:', a ** 2)  # Scalar exponentiation
# Output: a ** 2: [ 1  4  9 16 25]

print('-' * 40)  # Print a separator line
# Output: ----------------------------------------

# Dot product
c = np.array([[1], [2], [3], [4], [5]])  # Create a 2D array 'c'
print(c)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]
print('a.dot(c):', a.dot(c))  # Dot product of 'a' and 'c'
# Output: a.dot(c): [55]

print('-' * 40, '\nstatistics over whole array (all elements)')
# Output: ---------------------------------------- 
#         statistics over whole array (all elements)

# Statistical operations over the entire array
print('c min:', c.min())  # Minimum value in array 'c'
# Output: c min: 1
print('c max:', c.max())  # Maximum value in array 'c'
# Output: c max: 5
print('c sum:', c.sum())  # Sum of all elements in array 'c'
# Output: c sum: 15
print('c mean:', c.mean())  # Mean of all elements in array 'c'
# Output: c mean: 3.0

print('-' * 40, '\nstatistics by axis')
# Output: ---------------------------------------- 
#         statistics by axis

# Creating a 2D array 'd'
d = np.array([[10, 20], [30, 40], [50, 60], [70, 80]])
print(d)
# Output:
# [[10 20]
#  [30 40]
#  [50 60]
#  [70 80]]

# Statistical operations by axis
print('d min (columns):', d.min(axis=0))  # Minimum value along columns of array 'd'
# Output: d min (columns): [10 20]
print('d min (rows):', d.min(axis=1))  # Minimum value along rows of array 'd'
# Output: d min (rows): [10 30 50 70]
print('d max (columns):', d.max(axis=0))  # Maximum value along columns of array 'd'
# Output: d max (columns): [70 80]
print('d max (rows):', d.max(axis=1))  # Maximum value along rows of array 'd'
# Output: d max (rows): [20 40 60 80]
print('d sum (columns):', d.sum(axis=0))  # Sum along columns of array 'd'
# Output: d sum (columns): [160 200]
print('d sum (rows):', d.sum(axis=1))  # Sum along rows of array 'd'
# Output: d sum (rows): [ 30  70 110 150]
print('d mean (columns):', d.mean(axis=0))  # Mean along columns of array 'd'
# Output: d mean (columns): [40. 50.]
print('d mean (rows):', d.mean(axis=1))  # Mean along rows of array 'd'
# Output: d mean (rows): [15. 35. 55. 75.]

a: [1 2 3 4 5]
b: [1. 2. 1. 2. 1.]
a + b: [2. 4. 4. 6. 6.]
a - b: [0. 0. 2. 2. 4.]
a * b: [1. 4. 3. 8. 5.]
a / b: [1. 1. 3. 2. 5.]
----------------------------------------
a + 10: [11 12 13 14 15]
a - 10: [-9 -8 -7 -6 -5]
a * 10: [10 20 30 40 50]
a / 10: [0.1 0.2 0.3 0.4 0.5]
a ** 2: [ 1  4  9 16 25]
----------------------------------------
[[1]
 [2]
 [3]
 [4]
 [5]]
a.dot(c): [55]
---------------------------------------- 
statistics over whole array (all elements)
c min: 1
c max: 5
c sum: 15
c mean: 3.0
---------------------------------------- 
statistics by axis
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
d min (columns): [10 20]
d min (rows): [10 30 50 70]
d max (columns): [70 80]
d max (rows): [20 40 60 80]
d sum (columns): [160 200]
d sum (rows): [ 30  70 110 150]
d mean (columns): [40. 50.]
d mean (rows): [15. 35. 55. 75.]


### Matrix Operations with NumPy 🧮✨

In [3]:
import numpy as np  # Importing the numpy module

# Defining numpy arrays
a = np.array([[3, 1], [1, 3]])  # Matrix 'a'
b = np.array([[3, 5], [4, 2]])  # Matrix 'b'
'''
    |3 1| * |3 5|
    |1 3|   |4 2|

    |3*3 + 1*4    3*5 + 1*2|  ==> |13   17|
    |1*3 + 3*4    1*5 + 3*2|      |15   11|
'''

# Performing matrix multiplication using dot product
z = np.dot(a, b)
print(f'Dot product of the two arrays:\n{z}')
# Output:
# Dot product of the two arrays:
# [[13 17]
#  [15 11]]

# Summing all elements of array 'b'
z = np.sum(b)
print(f'Sum of array b: {z}')  # Output => 3+5+4+2 = 14
# Output:
# Sum of array b: 14

# Adding two arrays element-wise
print(f'Addition of two arrays:\n{np.add(a, b)}')
# Output:
# Addition of two arrays:
# [[6 6]
#  [5 5]]

# Calculating the mean of array 'a'
print(f'Mean of array a: {np.mean(a)}')
# Output:
# Mean of array a: 2.0

# Performing matrix multiplication using matmul function
print(f'Matrix multiplication of two arrays:\n{np.matmul(a, b)}')  # dot product
# Output:
# Matrix multiplication of two arrays:
# [[13 17]
#  [15 11]]

# Element-wise multiplication of two arrays
print(f'Multiplication of two arrays:\n{np.multiply(a, b)}')
# Output:
# Multiplication of two arrays:
# [[ 9  5]
#  [ 4  6]]

Dot product of the two arrays:
[[13 17]
 [15 11]]
Sum of array b: 14
Addition of two arrays:
[[6 6]
 [5 5]]
Mean of array a: 2.0
Matrix multiplication of two arrays:
[[13 17]
 [15 11]]
Multiplication of two arrays:
[[9 5]
 [4 6]]
